* configure.ac: Quote strings throughout in good Autoconf style. 	Remove AC_PROG_YACC invocation. Search for docbook2dvi, et al and 	expect using AC_PATH_PROG. Remove DJ_AC_PATH_DOCBOOK in favour of 	existing macros. Remove stale BOARDS and CONFIG substs. Ensure Tcl 	is at version 8.3 or greater. 	* configure: Regenerate. 	* acinclude.m4: Remove. 	* aclocal.m4: Regenerate. 	* Makefile.in: Likewise. 	* doc/Makefile.am (%.pdf: %.sgml): Use $(DOCBOOK2PDF). 	(%.dvi: %.sgml): Use $(DOCBOOK2DVI). 	(%.html: %.sgml): Use $(DOCBOOK2HTML). 	* doc/Makefile.in: Regenerate. 	* example/Makefile.in: Likewise. 	* testsuite/Makefile.in: Likewise. 	* testsuite/libdejagnu/Makefile.in: Likewise. 	* TODO: Update.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -273,7 +273,7 @@ PACKAGE_BUGREPORT=
 
 ac_unique_file="runtest.exp"
 ac_subdirs_all="$ac_subdirs_all example/calc example/hello"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE YACC EXPECT DOCBOOK BOARDS CONFIG subdirs LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE DOCBOOK2DVI DOCBOOK2PDF DOCBOOK2HTML EXPECT subdirs LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -817,11 +817,6 @@ Optional Features:
 			  (and sometimes confusing) to the casual installer
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
-
-Optional Packages:
-  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
-  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-docbook       directory where the db2 sgml tools are
 
 Some influential environment variables:
   CC          C compiler command
@@ -3384,46 +3379,126 @@ test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL}'
 test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 
 
-for ac_prog in 'bison -y' byacc
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
+
+# Extract the first word of "docbook2dvi", so it can be a program name with args.
+set dummy docbook2dvi; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_YACC+set}" = set; then
+if test "${ac_cv_path_DOCBOOK2DVI+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  if test -n "$YACC"; then
-  ac_cv_prog_YACC="$YACC" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+  case $DOCBOOK2DVI in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_DOCBOOK2DVI="$DOCBOOK2DVI" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
 for as_dir in $PATH
 do
   IFS=$as_save_IFS
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_YACC="$ac_prog"
+    ac_cv_path_DOCBOOK2DVI="$as_dir/$ac_word$ac_exec_ext"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
 done
 done
 
+  test -z "$ac_cv_path_DOCBOOK2DVI" && ac_cv_path_DOCBOOK2DVI="false"
+  ;;
+esac
 fi
-fi
-YACC=$ac_cv_prog_YACC
-if test -n "$YACC"; then
-  echo "$as_me:$LINENO: result: $YACC" >&5
-echo "${ECHO_T}$YACC" >&6
+DOCBOOK2DVI=$ac_cv_path_DOCBOOK2DVI
+
+if test -n "$DOCBOOK2DVI"; then
+  echo "$as_me:$LINENO: result: $DOCBOOK2DVI" >&5
+echo "${ECHO_T}$DOCBOOK2DVI" >&6
 else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
-  test -n "$YACC" && break
+# Extract the first word of "docbook2pdf", so it can be a program name with args.
+set dummy docbook2pdf; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_DOCBOOK2PDF+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $DOCBOOK2PDF in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_DOCBOOK2PDF="$DOCBOOK2PDF" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_DOCBOOK2PDF="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
 done
-test -n "$YACC" || YACC="yacc"
+done
+
+  test -z "$ac_cv_path_DOCBOOK2PDF" && ac_cv_path_DOCBOOK2PDF="false"
+  ;;
+esac
+fi
+DOCBOOK2PDF=$ac_cv_path_DOCBOOK2PDF
+
+if test -n "$DOCBOOK2PDF"; then
+  echo "$as_me:$LINENO: result: $DOCBOOK2PDF" >&5
+echo "${ECHO_T}$DOCBOOK2PDF" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+# Extract the first word of "docbook2html", so it can be a program name with args.
+set dummy docbook2html; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_DOCBOOK2HTML+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $DOCBOOK2HTML in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_DOCBOOK2HTML="$DOCBOOK2HTML" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_DOCBOOK2HTML="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_DOCBOOK2HTML" && ac_cv_path_DOCBOOK2HTML="false"
+  ;;
+esac
+fi
+DOCBOOK2HTML=$ac_cv_path_DOCBOOK2HTML
+
+if test -n "$DOCBOOK2HTML"; then
+  echo "$as_me:$LINENO: result: $DOCBOOK2HTML" >&5
+echo "${ECHO_T}$DOCBOOK2HTML" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
 
 
 # Extract the first word of "expect", so it can be a program name with args.
@@ -3471,56 +3546,26 @@ echo "$as_me: error: unable to locate expect" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-
-echo "$as_me:$LINENO: checking for Docbook tools" >&5
-echo $ECHO_N "checking for Docbook tools... $ECHO_C" >&6
-
-# Check whether --with-oskith or --without-oskith was given.
-if test "${with_oskith+set}" = set; then
-  withval="$with_oskith"
-  with_docbook=${withval}
-fi;
-if test "${ac_cv_c_docbook+set}" = set; then
+echo "$as_me:$LINENO: checking Tcl version 8.3 or greater" >&5
+echo $ECHO_N "checking Tcl version 8.3 or greater... $ECHO_C" >&6
+if test "${ac_cv_dg_tcl_modern+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
 
-if test x"${with_docbook}" != x ; then
-  if test -f ${with_docbook}/db2html ; then
-    ac_cv_c_docbook=`(cd ${with_docbook}; pwd)`
-  else
-    { { echo "$as_me:$LINENO: error: ${with_docbook} directory doesn't contain SGML tools" >&5
-echo "$as_me: error: ${with_docbook} directory doesn't contain SGML tools" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-fi
+  ac_cv_dg_tcl_modern=`$EXPECT << EOF
+if [ expr \\${tcl_version} >= 8.3  ] then { puts yes } else { puts no }
+EOF`
 
 fi
 
-if test x"${ac_cv_c_docbook}" = x ; then
-    for i in $ac_default_prefix/bin /usr/local/bin $OSKITHDIR/../bin /usr/bin /bin /opt /home; do
-		if test -f $i/db2html ; then
-	    ac_cv_c_docbook=$i
-	    break
-	fi
-    done
-fi
-
-if test x"${ac_cv_c_docbook}" = x ; then
-    echo "$as_me:$LINENO: result: none" >&5
-echo "${ECHO_T}none" >&6
+if test x${ac_cv_dg_tcl_modern} = xyes ; then
+  echo "$as_me:$LINENO: result: ${ac_cv_dg_tcl_modern}" >&5
+echo "${ECHO_T}${ac_cv_dg_tcl_modern}" >&6
 else
-    DOCBOOK="${ac_cv_c_docbook}"
-    echo "$as_me:$LINENO: result: ${ac_cv_c_docbook}" >&5
-echo "${ECHO_T}${ac_cv_c_docbook}" >&6
+  { { echo "$as_me:$LINENO: error: Tcl 8.3 or greater is required" >&5
+echo "$as_me: error: Tcl 8.3 or greater is required" >&2;}
+   { (exit 1); exit 1; }; }
 fi
-
-
-
-
-BOARDS='$(boards)'
-
-CONFIG='$(config)'
-
 
 
 
@@ -4252,11 +4297,10 @@ s,@ac_ct_CXX@,$ac_ct_CXX,;t t
 s,@CXXDEPMODE@,$CXXDEPMODE,;t t
 s,@am__fastdepCXX_TRUE@,$am__fastdepCXX_TRUE,;t t
 s,@am__fastdepCXX_FALSE@,$am__fastdepCXX_FALSE,;t t
-s,@YACC@,$YACC,;t t
+s,@DOCBOOK2DVI@,$DOCBOOK2DVI,;t t
+s,@DOCBOOK2PDF@,$DOCBOOK2PDF,;t t
+s,@DOCBOOK2HTML@,$DOCBOOK2HTML,;t t
 s,@EXPECT@,$EXPECT,;t t
-s,@DOCBOOK@,$DOCBOOK,;t t
-s,@BOARDS@,$BOARDS,;t t
-s,@CONFIG@,$CONFIG,;t t
 s,@subdirs@,$subdirs,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
