* configure.ac: Use AC_PATH_PROG to find expect(1). 	(DJ_AC_PATH_TCLSH): Remove unneeded invocation. 	* acinclude.m4 (DJ_AC_PATH_TCLSH): Remove (unused). 	(DJ_AC_STL): Likewise. 	* configure: Regenerate. 	* aclocal.m4: Likewise. 	* configure: Likewise. 	* Makefile.in: Likewise. 	* doc/Makefile.in: Likewise. 	* example/Makefile.in: Likewise. 	* testsuite/Makefile.in: Likewise. 	* testsuite/libdejagnu/Makefile.in: Likewise. 	* TODO: Update.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -273,7 +273,7 @@ PACKAGE_BUGREPORT=
 
 ac_unique_file="runtest.exp"
 ac_subdirs_all="$ac_subdirs_all example/calc example/hello"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE YACC DOCBOOK tclsh TCLSH BOARDS CONFIG subdirs LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE YACC EXPECT DOCBOOK BOARDS CONFIG subdirs LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -822,7 +822,6 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-docbook       directory where the db2 sgml tools are
-  --with-tclinclude       directory where tcl headers are
 
 Some influential environment variables:
   CC          C compiler command
@@ -3385,7 +3384,6 @@ test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL}'
 test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 
 
-
 for ac_prog in 'bison -y' byacc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -3428,10 +3426,54 @@ done
 test -n "$YACC" || YACC="yacc"
 
 
+# Extract the first word of "expect", so it can be a program name with args.
+set dummy expect; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_EXPECT+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $EXPECT in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_EXPECT="$EXPECT" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_EXPECT="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
 
-dirlist=".. ../../ ../../.. ../../../.. ../../../../.. ../../../../../.. ../../../../../../.. ../../../../../../../.. ../../../../../../../../.. ../../../../../../../../../.."
-echo "$as_me:$LINENO: checking for docbook tools" >&5
-echo $ECHO_N "checking for docbook tools... $ECHO_C" >&6
+  ;;
+esac
+fi
+EXPECT=$ac_cv_path_EXPECT
+
+if test -n "$EXPECT"; then
+  echo "$as_me:$LINENO: result: $EXPECT" >&5
+echo "${ECHO_T}$EXPECT" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test -z $ac_cv_path_EXPECT ; then
+   { { echo "$as_me:$LINENO: error: unable to locate expect" >&5
+echo "$as_me: error: unable to locate expect" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+echo "$as_me:$LINENO: checking for Docbook tools" >&5
+echo $ECHO_N "checking for Docbook tools... $ECHO_C" >&6
 
 # Check whether --with-oskith or --without-oskith was given.
 if test "${with_oskith+set}" = set; then
@@ -3472,104 +3514,6 @@ else
 echo "${ECHO_T}${ac_cv_c_docbook}" >&6
 fi
 
-
-
-
-
-dirlist=".. ../../ ../../../ ../../../../ ../../../../../ ../../../../../../ ../
-../../../../../.. ../../../../../../../.. ../../../../../../../../.. ../../../..
-/../../../../../.."
-no_itcl=true
-echo "$as_me:$LINENO: checking for the tclsh program" >&5
-echo $ECHO_N "checking for the tclsh program... $ECHO_C" >&6
-
-# Check whether --with-tclinclude or --without-tclinclude was given.
-if test "${with_tclinclude+set}" = set; then
-  withval="$with_tclinclude"
-  with_tclinclude=${withval}
-fi;
-if test "${ac_cv_path_tclsh+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-
-if test x"${with_tclinclude}" != x ; then
-  if test -f ${with_tclinclude}/tclsh ; then
-    ac_cv_path_tclsh=`(cd ${with_tclinclude}; pwd)`
-  elif test -f ${with_tclinclude}/src/tclsh ; then
-    ac_cv_path_tclsh=`(cd ${with_tclinclude}/src; pwd)`
-  else
-    { { echo "$as_me:$LINENO: error: ${with_tclinclude} directory doesn't contain tclsh" >&5
-echo "$as_me: error: ${with_tclinclude} directory doesn't contain tclsh" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-fi
-
-fi
-
-
-if test x"${ac_cv_path_tclsh}" = x ; then
-        for i in $dirlist; do
-        if test -n "`ls -dr $srcdir/$i/tcl* 2>/dev/null`" ; then
-            tclpath=$srcdir/$i
-            break
-        fi
-    done
-
-            for i in `ls -dr $tclpath/tcl* 2>/dev/null ` ; do
-        if test -f $i/src/tclsh ; then
-          ac_cv_path_tclsh=`(cd $i/src; pwd)`/tclsh
-          break
-        fi
-    done
-fi
-
-if test x"${ac_cv_path_tclsh}" = x ; then
-   echo "$as_me:$LINENO: result: none" >&5
-echo "${ECHO_T}none" >&6
-   # Extract the first word of "tclsh", so it can be a program name with args.
-set dummy tclsh; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_tclsh+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $tclsh in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_tclsh="$tclsh" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_tclsh="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-  ;;
-esac
-fi
-tclsh=$ac_cv_path_tclsh
-
-if test -n "$tclsh"; then
-  echo "$as_me:$LINENO: result: $tclsh" >&5
-echo "${ECHO_T}$tclsh" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-else
-   echo "$as_me:$LINENO: result: ${ac_cv_path_tclsh}" >&5
-echo "${ECHO_T}${ac_cv_path_tclsh}" >&6
-fi
-TCLSH="${ac_cv_path_tclsh}"
 
 
 
@@ -4309,9 +4253,8 @@ s,@CXXDEPMODE@,$CXXDEPMODE,;t t
 s,@am__fastdepCXX_TRUE@,$am__fastdepCXX_TRUE,;t t
 s,@am__fastdepCXX_FALSE@,$am__fastdepCXX_FALSE,;t t
 s,@YACC@,$YACC,;t t
+s,@EXPECT@,$EXPECT,;t t
 s,@DOCBOOK@,$DOCBOOK,;t t
-s,@tclsh@,$tclsh,;t t
-s,@TCLSH@,$TCLSH,;t t
 s,@BOARDS@,$BOARDS,;t t
 s,@CONFIG@,$CONFIG,;t t
 s,@subdirs@,$subdirs,;t t
